name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"


<!DOCTYPE html>
<html lang="eng">
<head>
<title>Registration Form</title>
</head>
<body>
 <h1 align="center"style="color:#0F93A7">Registration Form</h1>
 <form>
 <table border="2" height="400px" width="40%" align="center">
 <!-----ROW 1------>
 <tr>
 <th>Frist Name:</th>
 <th><input type="text" placeholder="Frist Name" name=""></th>
 </tr>
 <!-----ROW 2------>
 <tr>
 <th>Second Name:</th>
 <th><input type="text" placeholder="Second Name" name=""></th>
 </tr>
 <!-----ROW 3------>
 <tr>
 <th>Mobile No:</th>
 <th>
 <select>
 <option>+91</option>
 <option>+83</option>
 <option>+234</option>
 <option>+71</option>
 </select>
 <input type="number" placeholder="Mobile No" name=""></th>
 </tr>
 <!-----ROW 4------>
 <tr>
 <th>Date of Birth:</th>
 <th><input type="DateTime-local" Name="placeholder"></th>
 </tr>
 <!-----ROW 5------>
 <tr>
 <th>Email id:</th>
 <th><input type="id" placeholder="Email" name=""></th>
 </tr>
 <!-----ROW 6------>
 <tr>
 <th>Website URL:</th>
 <th><input type="URL" placeholder="Website URL" name=""></th>
 </tr>
 <!-----ROW 7------>
 <tr>
 <th>Gender:</th>
 <th><input type="Radio" placeholder="Male" >male
 <input type="Radio" placeholder="Female" >female</th>
 </tr>
 <!-----ROW 8------>
 <tr>
 <th>Ability to learn new technology:</th>
 <th><input type="range" placeholder="ability to learn " name=""></th>
 </tr>
 <!-----ROW 9------>
 <tr>
 <th>Time of registration:</th>
 <th><input type="Timer"></th>
 </tr>
 <th colspan="2">
 <input type="Submit"style="background-color:#68B120;">
 <input type="Reset"style="background-color:#FF3346;">
 </th>
 </tr>
 </table>
</body>
</html>

